# esto vendria a ser el package del node 
name: smartur
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.0.10+1
  google_sign_in: ^7.2.0
  http: ^1.6.0
  local_auth: ^2.1.6
  local_auth_android: any
  lottie: ^3.3.2
  shared_preferences: ^2.5.4
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/lottie/
    - assets/svg/
    - assets/fonts/

  fonts:
      - family: CalSans
        fonts:
          - asset: assets/fonts/CalSans-Regular.ttf

      - family: Outfit
        fonts:
          - asset: assets/fonts/Outfit-VariableFont_wght.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/imgs/logo.png"