# esto vendria a ser el package del node aaron
name: app_smartur
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
      - family: CalSans
        fonts:
          - asset: assets/fonts/CalSans-Regular.ttf

      - family: Outfit
        fonts:
          - asset: assets/fonts/Outfit-VariableFont_wght.ttf